### ISSUE TITLE
a problem...

### ISSUE THREAD

**Issue by siaery** [j3tm0t0/check_cloudwatch#3]
i am using this script to monitor my RDS, but it does not work....
i got this error:

[1347108288] SERVICE NOTIFICATION: nagiosadmin;rds1;CPU;UNKNOWN;notify-service-by-email;CPUUtilization UNKNOWN - failed to retrieve data. check arguments.

i can get the response from command line:
# /usr/lib64/nagios/plugins/check_cloudwatch ap-northeast-1 CPUUtilization "Average" "AWS/RDS" "DBInstanceIdentifier=nagiostest" 360 60 80

CPUUtilization OK - 7.692 Percent

but it does not work with nagios... who can help me??

**Comment by siaery** [comment]
this is a part of my configure file
define command{
        command_name         check-cloudwatch
        command_line    $USER1$/check_cloudwatch $ARG1$ $ARG2$ $ARG3$ $ARG4$ $ARG5$ $ARG6$ $ARG7$ $ARG8$}

define host{
        use                     rds-instance
        host_name               rds1
        alias                   nagiostest
        address                 nagiostest.XXXXXXXXX.ap-northeast-1.rds.amazonaws.com #my rds endpoint, it works
}

define hostgroup{
        hostgroup_name  ap-northeast-1
        members         rds1
}

define service{
        use                             generic-service
        host_name                       rds1
        service_description             CPU
        check_command                   check-cloudwatch!$HOSTGROUPNAME$!CPUUtilization!"Average"!"AWS/RDS"!"DBInstanceIdentifier=$HOSTALIAS$"!360!60!90
}

**Comment by siaery** [comment]
resolved!
because i did not set the PATH for the Nagios user.Sorry for this issue....

**Comment by nagarjunadn** [comment]
Hi Siaery,

I am also having the same issue i can get the response from command line. Could you please suggest me how did you set PATH for Nagios user.

Thanks in advance,
Nagarjuna
