### ISSUE TITLE
Autoscaling Group metrics

### ISSUE THREAD

**Issue by cirk0** [j3tm0t0/check_cloudwatch#4]
When I'm requesting metrics for an autoscaling group ( namespace AWS/EC2 and dimension "Name=AutoScalingGroupName,Value=xxxx"

it returns:

./check_cloudwatch: 42: ./check_cloudwatch: [[: not found
CPUUtilization OK - 3.181333333333334 Percent

**Comment by cirk0** [comment]
Yea well, just realised how old this repo is but anyway, the solution was to just modify #!/bin/sh to #!/bin/bash

**Comment by j3tm0t0** [comment]
Yeah, this was written long before the light-weight python based AWS CLI is released.
I'd recommend other way to call AWS APIs than using JAVA based CLI.
